'use strict';

const USER_ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  SELLER: 'SELLER',
  CUSTOMER: 'CUSTOMER',
});

const VEHICLE_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  SOLD: 'SOLD',
});

const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  CONTACTED: 'CONTACTED',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
});

const SALE_CHANNEL = Object.freeze({
  ONLINE: 'ONLINE',
  OFFLINE: 'OFFLINE',
});

const FUEL_TYPE = Object.freeze({
  PETROL: 'PETROL',
  DIESEL: 'DIESEL',
  ELECTRIC: 'ELECTRIC',
  HYBRID: 'HYBRID',
  PLUGIN_HYBRID: 'PLUGIN_HYBRID',
  OTHER: 'OTHER',
});

const TRANSMISSION = Object.freeze({
  MANUAL: 'MANUAL',
  AUTOMATIC: 'AUTOMATIC',
  CVT: 'CVT',
  DUAL_CLUTCH: 'DUAL_CLUTCH',
  OTHER: 'OTHER',
});

const DRIVE_TYPE = Object.freeze({
  FWD: 'FWD',
  RWD: 'RWD',
  AWD: 'AWD',
  FOUR_WD: 'FOUR_WD',
});

const BODY_TYPE = Object.freeze({
  SEDAN: 'SEDAN',
  SUV: 'SUV',
  HATCHBACK: 'HATCHBACK',
  COUPE: 'COUPE',
  CONVERTIBLE: 'CONVERTIBLE',
  PICKUP: 'PICKUP',
  VAN: 'VAN',
  WAGON: 'WAGON',
  OTHER: 'OTHER',
});

const VEHICLE_CONDITION = Object.freeze({
  NEW: 'NEW',
  USED: 'USED',
  CERTIFIED_PRE_OWNED: 'CERTIFIED_PRE_OWNED',
});

const MILEAGE_UNIT = Object.freeze({
  KM: 'KM',
  MILES: 'MILES',
});

const EXPENSE_CATEGORY = Object.freeze({
  TRANSPORT: 'TRANSPORT',
  REPAIR: 'REPAIR',
  CUSTOMS: 'CUSTOMS',
  REGISTRATION: 'REGISTRATION',
  CLEANING: 'CLEANING',
  MAINTENANCE: 'MAINTENANCE',
  PARTS: 'PARTS',
  OTHER: 'OTHER',
});

const GENERAL_EXPENSE_CATEGORY = Object.freeze({
  RENT: 'RENT',
  UTILITIES: 'UTILITIES',
  SALARIES: 'SALARIES',
  MARKETING: 'MARKETING',
  SUPPLIES: 'SUPPLIES',
  OTHER: 'OTHER',
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PARTIAL: 'PARTIAL',
  PAID: 'PAID',
  REFUNDED: 'REFUNDED',
});

const SELLER_TYPE = Object.freeze({
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY',
});

module.exports = {
  USER_ROLES,
  VEHICLE_STATUS,
  ORDER_STATUS,
  SALE_CHANNEL,
  FUEL_TYPE,
  TRANSMISSION,
  DRIVE_TYPE,
  BODY_TYPE,
  VEHICLE_CONDITION,
  MILEAGE_UNIT,
  EXPENSE_CATEGORY,
  GENERAL_EXPENSE_CATEGORY,
  PAYMENT_STATUS,
  SELLER_TYPE,
};